### ISSUE TITLE
hyperschema

### ISSUE THREAD

**Issue by artemshapovalov** [aromanovich/jsl#10]
Please tell me whether it is possible to use the library for generating hyperschema? Or it is possible somehow expand the basic attributes?

**Comment by aromanovich** [comment]
Sorry for not answering earlier.

Currently JSL doesn't provide any means to generate hyperschemas and I don't plan to implement them unless someone makes a pull request.

However, it's possible to subclass `Document` (and `DocumentMeta` if necessary) or any of the fields to make them accept new parameters and produce hyperschemas.
