### ISSUE TITLE
RECURSIVE_REFERENCE_CONSTANT not working under scopes

### ISSUE THREAD

**Issue by sebdiem** [aromanovich/jsl#14]
Hi,

    class Test(jsl.Document):
        with jsl.Scope('test') as test:
            test.field = jsl.DocumentField(jsl.RECURSIVE_REFERENCE_CONSTANT)

generates an infinite recursion loop whereas

    class Test(jsl.Document):
         test.field = jsl.DocumentField(jsl.RECURSIVE_REFERENCE_CONSTANT)

works fine.
Is it "normal" ?

**Comment by aromanovich** [comment]
Fixed in jsl==0.1.5.

Thanks for reporting the bug!

**Comment by sebdiem** [comment]
Thank you for fixing it so quickly ! and for this very useful tool.
