### ISSUE TITLE
Track changes with ChangeLog

### ISSUE THREAD

**Issue by playpauseandstop** [aromanovich/jsl#2]
Hi,

As an user of jsl I'd like to have an ability to track changes in recently released versions. There are many options on how to track these changes, but as jsl has one page doc I suggest just add new section to a docs. Thanks!

And many thanks for your work on library! Helps me describing JSON Schemas with ease!

**Comment by aromanovich** [comment]
Nice idea! I started to keep a [changelog](http://jsl.readthedocs.org/en/latest/#changelog).

I'm glad you find JSL useful. Please let me know if you miss some features or have more suggestions :)

**Comment by playpauseandstop** [comment]
Thanks! That's awesome!
