### ISSUE TITLE
Looks like commit with 0.0.10 version not pushed to master

### ISSUE THREAD

**Issue by playpauseandstop** [aromanovich/jsl#5]
Subj

[jsl/__init__.py still has 0.0.9 version](https://github.com/aromanovich/jsl/blob/master/jsl/__init__.py)

**Comment by aromanovich** [comment]
Yeah, I messed up a bit. I merged a [fix](https://github.com/aromanovich/jsl/pull/4), but didn't want to release from master (there are a lot of changes and it's going to be 0.1.0).
So I cherry-picked the fix on top of the [0.0.9 tag](https://github.com/aromanovich/jsl/tree/0.0.9), created a new tag [0.0.10](https://github.com/aromanovich/jsl/tree/0.0.10) and released it on PyPI.
