### ISSUE TITLE
No necessary to put whole license file content in setup script

### ISSUE THREAD

**Issue by playpauseandstop** [aromanovich/jsl#8]
I suggest to put only license abbr into license field in setup script as done [Django](https://github.com/django/django/blob/master/setup.py#L43), [Flask](https://github.com/mitsuhiko/flask/blob/master/setup.py#L61), and other Python libraries.

This definitely helps when using [pypi-cli](https://warehouse.python.org/project/pypi-cli/), like ``pypi info jsl``, and tries to find out latest jsl version released on PyPI. Now I need to scroll up to ``Latest release: ...`` line as whole license text printed there

Thanks!

**Comment by playpauseandstop** [comment]
Thanks!

**Comment by aromanovich** [comment]
Thanks for using JSL, I'm glad to have a constant feedback!
